Polish translation
CzBiX/wifi-password-android pull request #6
Opened 2017-01-03 20:38 UTC by Kucharskov

Amazing work by M. Kucharskov and Mezurashii.
Regards!

2017-01-09 08:25 UTC, CzBiX requested changes

2017-01-09 08:25 UTC, CzBiX commented on app/src/main/res/values-pl/strings.xml
> +	<!-- Translated with love by M. Kucharskov and Mezurashii -->
Please use space instead of tab

2017-01-09 08:25 UTC, CzBiX commented on app/src/main/res/values-pl/strings.xml
> +	<!-- Translated with love by M. Kucharskov and Mezurashii -->
Please use space instead of tab, thanks.

2017-01-09 13:39 UTC, Kucharskov commented
Its more important than new launguage in app. As if you couldnt do it yourself.
Anyways - fixed. Regards!

2017-01-10 08:09 UTC, merged

2017-01-10 08:14 UTC, CzBiX commented
It's the way of collaboration. I think you should know what's wrong as the author of this commit.
Modify your code without contact you may be bad manners, or maybe I'm too sensitive.

Anyway thanks your work.